### ISSUE TITLE
Connection to Database

### ISSUE THREAD

**Issue by krazydiam** [AbdulhakimZ/SMIS#1]
Hi Abdulhakim,

I tried what you said, importing the database to the SQL server. I have already imported the mdf file into the SQL server. My concern now is that I'm unsure of how to connect to the SMSEntitities since it seems that I can already connect to the SMS database. 

![Screenshot (251)](https://user-images.githubusercontent.com/100152800/235140818-1d81b164-8280-4d20-9182-abc42b619fd4.png)

**Comment by AbdulhakimZ** [comment]
To configure the database connectivity for the ASP.NET project, you need to modify the connection string in the [web.config](https://github.com/AbdulhakimZ/SMIS/blob/main/SMS/Web.config) file. You should change the value of the "data source" attribute to match your own SQL Server name.

You can do this by opening the [web.config](https://github.com/AbdulhakimZ/SMIS/blob/main/SMS/Web.config) file located in the project directory, and then finding the connection string that contains the data source attribute. In this case, the connection string is named "SMSEntities". You need to modify the value of the data source attribute from "AZ" to your own SQL Server name.

After making the change, the modified connection string should look something like this:

`<add name="SMSEntities" connectionString="metadata=res://*/Models.SMSDB.csdl|res://*/Models.SMSDB.ssdl|res://*/Models.SMSDB.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=YourSqlServerName;initial catalog=SMS;integrated security=True;multipleactiveresultsets=True;application name=EntityFramework&quot;" providerName="System.Data.EntityClient" />`

**Comment by krazydiam** [comment]
Thank you for that. I wasn't able to see that I should change the data source in the SMSEntities connection string. I changed the "AZ" to my own SQL server name and was able to log in to the website easily. Thank you very much AbdulhakimZ for taking the time to acknowledge and answer my queries. Your website will surely be a great help to us!
